export const GET_MESAS_LOADING = 'GET_MESAS_LOADING'
export const GET_MESAS_SUCCESS = 'GET_MESAS_SUCCESS'
export const GET_MESAS_ERROR = 'GET_MESAS_ERROR'

export const GET_RESERVAS_SUCCESS = 'GET_RESERVAS_SUCCESS'

export const GET_PRODUCTOS_LOADING = 'GET_PRODUCTOS_LOADING'
export const GET_PRODUCTOS_SUCCESS = 'GET_PRODUCTOS_SUCCESS'
export const GET_PRODUCTOS_ERROR = 'GET_PRODUCTOS_ERROR'