export const GET_MESAS_LOADING = 'GET_MESAS_LOADING'
export const GET_MESAS_SUCCESS = 'GET_MESAS_SUCCESS'
export const GET_MESAS_ERROR = 'GET_MESAS_ERROR'

export const GET_RESERVAS_SUCCESS = 'GET_RESERVAS_SUCCESS'