export const GET_USERS_LOADING = 'GET_USERS_LOADING'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'GET_USERS_ERROR'

export const GET_PLATOS_LOADING = 'GET_PLATOS_LOADING'
export const GET_PLATOS_SUCCESS = 'GET_PLATOS_SUCCESS'
export const GET_PLATOS_ERROR = 'GET_PLATOS_ERROR'